const STOP_WORDS = new Set([
  // Articles
  "a",
  "an",
  "the",

  // Prepositions
  "in",
  "on",
  "at",
  "by",
  "for",
  "with",
  "without",
  "of",
  "to",
  "from",
  "up",
  "down",
  "over",
  "under",
  "above",
  "below",
  "between",
  "among",
  "through",
  "during",
  "before",
  "after",
  "since",
  "until",
  "within",
  "against",
  "across",
  "around",
  "behind",
  "beside",
  "beyond",
  "inside",
  "outside",
  "near",
  "next",
  "onto",
  "upon",
  "into",
  "toward",
  "towards",

  // Conjunctions
  "and",
  "or",
  "but",
  "yet",
  "so",
  "nor",
  "although",
  "though",
  "because",
  "since",
  "unless",
  "while",
  "whereas",
  "if",
  "whether",
  "that",
  "which",
  "who",
  "whom",
  "whose",

  // Pronouns
  "i",
  "me",
  "my",
  "mine",
  "you",
  "your",
  "yours",
  "he",
  "him",
  "his",
  "she",
  "her",
  "hers",
  "it",
  "its",
  "we",
  "us",
  "our",
  "ours",
  "they",
  "them",
  "their",
  "theirs",
  "this",
  "that",
  "these",
  "those",
  "what",
  "who",
  "which",
  "where",
  "when",
  "why",
  "how",

  // Common verbs (action words that don't add component meaning)
  "is",
  "am",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "doing",
  "will",
  "would",
  "could",
  "should",
  "may",
  "might",
  "must",
  "can",
  "shall",
  "ought",
  "get",
  "got",
  "getting",
  "go",
  "goes",
  "went",
  "going",
  "gone",

  // UI-specific action words (keep semantic meaning but often redundant)
  "create",
  "make",
  "build",
  "add",
  "include",
  "put",
  "place",
  "insert",
  "generate",
  "design",
  "develop",
  "construct",
  "show",
  "display",
  "render",
  "draw",
  "want",
  "need",
  "like",
  "would",
  "please",
  "help",
  "can",
  "could",
  "should",

  // Filler words and phrases
  "also",
  "just",
  "only",
  "even",
  "still",
  "already",
  "yet",
  "again",
  "once",
  "twice",
  "here",
  "there",
  "where",
  "everywhere",
  "anywhere",
  "somewhere",
  "now",
  "then",
  "always",
  "never",
  "sometimes",
  "often",
  "usually",
  "frequently",
  "rarely",
  "seldom",
  "hardly",
  "barely",
  "almost",
  "quite",
  "very",
  "too",
  "so",
  "such",
  "rather",
  "pretty",
  "really",
  "truly",
  "actually",
  "basically",
  "literally",
  "obviously",
  "clearly",
  "certainly",
  "definitely",
  "probably",
  "possibly",
  "maybe",
  "perhaps",
  "somehow",
  "somewhat",

  // Quantifiers (keep numbers but remove vague quantities)
  "some",
  "any",
  "many",
  "much",
  "few",
  "little",
  "several",
  "various",
  "different",
  "same",
  "other",
  "another",
  "each",
  "every",
  "all",
  "both",
  "either",
  "neither",
  "most",
  "more",
  "less",
  "least",
  "enough",
  "plenty",

  // Polite expressions
  "please",
  "thanks",
  "thank",
  "sorry",
  "excuse",
  "pardon",
]);

const MULTI_WORD_PHRASES = new Map([
  // UI Components
  ["sign up", "signup"],
  ["log in", "login"],
  ["log out", "logout"],
  ["sign in", "signin"],
  ["sign out", "signout"],
  ["drop down", "dropdown"],
  ["text area", "textarea"],
  ["check box", "checkbox"],
  ["radio button", "radio"],
  ["file upload", "fileupload"],
  ["date picker", "datepicker"],
  ["time picker", "timepicker"],
  ["color picker", "colorpicker"],
  ["search bar", "searchbar"],
  ["search box", "searchbox"],
  ["nav bar", "navbar"],
  ["navigation bar", "navbar"],
  ["side bar", "sidebar"],
  ["tool bar", "toolbar"],
  ["progress bar", "progressbar"],
  ["scroll bar", "scrollbar"],
  ["menu bar", "menubar"],
  ["tab bar", "tabbar"],
  ["dark mode", "darkmode"],
  ["light mode", "lightmode"],

  // Form elements
  ["remember me", "rememberme"],
  ["forgot password", "forgotpassword"],
  ["confirm password", "confirmpassword"],
  ["repeat password", "repeatpassword"],
  ["first name", "firstname"],
  ["last name", "lastname"],
  ["full name", "fullname"],
  ["user name", "username"],
  ["email address", "email"],
  ["phone number", "phone"],
  ["zip code", "zipcode"],
  ["postal code", "postalcode"],
  ["date of birth", "dateofbirth"],
  ["terms of service", "termsofservice"],
  ["privacy policy", "privacypolicy"],

  // Layout terms
  ["flex box", "flexbox"],
  ["grid layout", "grid"],
  ["card layout", "card"],
  ["list view", "list"],
  ["table view", "table"],
  ["gallery view", "gallery"],

  // Actions
  ["click here", "click"],
  ["read more", "readmore"],
  ["learn more", "learnmore"],
  ["view all", "viewall"],
  ["show more", "showmore"],
  ["load more", "loadmore"],
  ["get started", "getstarted"],

  // States
  ["logged in", "loggedin"],
  ["signed in", "signedin"],
  ["checked out", "checkedout"],
  ["sold out", "soldout"],
  ["coming soon", "comingsoon"],

  // Boolean phrases
  ["is required", "required"],
  ["is optional", "optional"],
  ["is disabled", "disabled"],
  ["is hidden", "hidden"],
  ["is visible", "visible"],
  ["is active", "active"],
  ["is inactive", "inactive"],
]);

const CONTRACTIONS = new Map([
  ["don't", "do not"],
  ["won't", "will not"],
  ["can't", "cannot"],
  ["n't", " not"],
  ["'re", " are"],
  ["'ve", " have"],
  ["'ll", " will"],
  ["'d", " would"],
  ["'m", " am"],
  ["'s", " is"],
]);

const PRESERVE_WORDS = new Set([
  "form",
  "button",
  "input",
  "select",
  "option",
  "label",
  "field",
  "text",
  "number",
  "email",
  "password",
  "submit",
  "reset",
  "search",
  "filter",
  "sort",
  "order",
  "list",
  "item",
  "card",
  "modal",
  "popup",
  "dialog",
  "alert",
  "notification",
  "header",
  "footer",
  "sidebar",
  "navbar",
  "menu",
  "tab",
  "panel",
  "section",
  "container",
  "wrapper",
  "row",
  "column",
  "grid",
  "flex",
  "table",
  "cell",
  "image",
  "icon",
  "logo",
  "avatar",
  "thumbnail",
  "gallery",
  "carousel",
  "slider",
  "chart",
  "graph",
  "map",
  "calendar",
  "date",
  "time",
  "clock",
  "timer",
  "progress",
  "loading",
  "spinner",
  "tooltip",
  "badge",
  "chip",
  "tag",
  "pill",
]);

const SYNONYMS = new Map([
  ["btn", "button"],
  ["pic", "image"],
  ["img", "image"],
  ["photo", "image"],
  ["txt", "text"],
  ["num", "number"],
  ["pw", "password"],
  ["pwd", "password"],
  ["usr", "user"],
  ["admin", "administrator"],
  ["config", "configuration"],
  ["pref", "preference"],
  ["prefs", "preferences"],
  ["auth", "authentication"],
  ["nav", "navigation"],
  ["doc", "document"],
  ["docs", "documentation"],
  ["info", "information"],
  ["desc", "description"],
  ["msg", "message"],
  ["notification", "alert"],
  ["notify", "alert"],
]);

export {
  STOP_WORDS,
  MULTI_WORD_PHRASES,
  CONTRACTIONS,
  PRESERVE_WORDS,
  SYNONYMS,
};